// stdlib_bundle.rs — Embedded stdlib sources

pub fn get_embedded_stdlib(name: &str) -> Option<&'static str> {
    let clean = name.strip_suffix(".lyn").unwrap_or(name);
    match clean {
        "array" => Some(include_str!("../../stdlib/array.lyn")),
        "async" => Some(include_str!("../../stdlib/async.lyn")),
        "base64" => Some(include_str!("../../stdlib/base64.lyn")),
        "cli" => Some(include_str!("../../stdlib/cli.lyn")),
        "collections" => Some(include_str!("../../stdlib/collections.lyn")),
        "config" => Some(include_str!("../../stdlib/config.lyn")),
        "crypto" => Some(include_str!("../../stdlib/crypto.lyn")),
        "csv" => Some(include_str!("../../stdlib/csv.lyn")),
        "datetime" => Some(include_str!("../../stdlib/datetime.lyn")),
        "dotenv" => Some(include_str!("../../stdlib/dotenv.lyn")),
        "functional" => Some(include_str!("../../stdlib/functional.lyn")),
        "glob" => Some(include_str!("../../stdlib/glob.lyn")),
        "hashlib" => Some(include_str!("../../stdlib/hashlib.lyn")),
        "hex" => Some(include_str!("../../stdlib/hex.lyn")),
        "http" => Some(include_str!("../../stdlib/http.lyn")),
        "init" => Some(include_str!("../../stdlib/init.lyn")),
        "io" => Some(include_str!("../../stdlib/io.lyn")),
        "json" => Some(include_str!("../../stdlib/json.lyn")),
        "logger" => Some(include_str!("../../stdlib/logger.lyn")),
        "lzw" => Some(include_str!("../../stdlib/lzw.lyn")),
        "math" => Some(include_str!("../../stdlib/math.lyn")),
        "middleware" => Some(include_str!("../../stdlib/middleware.lyn")),
        "net" => Some(include_str!("../../stdlib/net.lyn")),
        "os" => Some(include_str!("../../stdlib/os.lyn")),
        "pathlib" => Some(include_str!("../../stdlib/pathlib.lyn")),
        "platform" => Some(include_str!("../../stdlib/platform.lyn")),
        "prompt" => Some(include_str!("../../stdlib/prompt.lyn")),
        "random" => Some(include_str!("../../stdlib/random.lyn")),
        "re" => Some(include_str!("../../stdlib/re.lyn")),
        "secrets" => Some(include_str!("../../stdlib/secrets.lyn")),
        "shutil" => Some(include_str!("../../stdlib/shutil.lyn")),
        "socket" => Some(include_str!("../../stdlib/socket.lyn")),
        "string" => Some(include_str!("../../stdlib/string.lyn")),
        "sys" => Some(include_str!("../../stdlib/sys.lyn")),
        "template" => Some(include_str!("../../stdlib/template.lyn")),
        "term" => Some(include_str!("../../stdlib/term.lyn")),
        "test" => Some(include_str!("../../stdlib/test.lyn")),
        "time" => Some(include_str!("../../stdlib/time.lyn")),
        "urllib" => Some(include_str!("../../stdlib/urllib.lyn")),
        "uuid" => Some(include_str!("../../stdlib/uuid.lyn")),
        "validate" => Some(include_str!("../../stdlib/validate.lyn")),
        "web" => Some(include_str!("../../stdlib/web.lyn")),
        "websec" => Some(include_str!("../../stdlib/websec.lyn")),
        "xml" => Some(include_str!("../../stdlib/xml.lyn")),
        _ => None,
    }
}
